// Originally released under a custom license.
// This historical re-release is provided under the MIT License.
// See the LICENSE file in the repo root for details.
//
// https://github.com/nettlep

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
  ±                                                                          ±
  ±   Copyright (c) 1997 Paul D. Nettle.  All Rights Reserved.               ±
  ±                                                                          ±
  ±   [MAKEBUM.H   ] - MakeMap's header file                                 ±
  ±                                                                          ±
  ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

#define MAX_INFILES  3000
#define MAX_COLORS   256
#define MAX_SHADES   64

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

#define  MIN(A,B)    ((A) < (B) ? (A) : (B))
#define  MAX(A,B)    ((A) > (B) ? (A) : (B))

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

enum
{
   E_NONE = 0,
   E_BADPARMS,
   E_NOCREATE,
   E_NOWRITE,
   E_NONAMES
};

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

extern void _SPDXMakeTransTable(IMAGE *PaletteTable, IMAGE *TransTable, UINT number_colors, UINT tree_depth, UBYT *Palette, FLT Opacity);

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/

void  MakeImageMono(IMAGE *Image);
void  GetNames( INT NameCount );
void  PrintCopyright( void );
void  ExitSystem( INT ErrorCode );
void  ErrorExit( INT ErrorCode );
void  PrintErrorString( INT ErrorCode );
void  PrintUsage( INT ErrorCode );
void  Convert24To8( IMAGE *Image );
INT   MyWrite( INT Handle, void *Buffer, INT Length );

/*±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
  ±   [MAKEBUM.H   ] - End Of File                                           ±
  ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±*/
